version: 3.0.4
name: separated_row
description: Flutter package for rendering Row widget that injects the separator in between the children.
homepage: https://github.com/anisalibegic/separated_row
repository: https://github.com/anisalibegic/separated_row
issue_tracker: https://github.com/anisalibegic/separated_row/issues

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: Example usage.
    path: screenshots/example.gif