name: separated_row
description: Flutter package for rendering Row widget that injects the separator in between the children.
version: 2.0.0
homepage: https://github.com/anisalibegic/separated_row

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
