name: separated_row
description: Flutter package for rendering Row widget that injects the separator in between the children.
version: 1.0.0+2
author: Anis Alibegić <anis.alibegic@gmail.com>
homepage: https://github.com/grandpa-guru/separated_row

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: